### ISSUE TITLE
I want to add a hamburger menu on navigation bar 

### ISSUE THREAD

**Issue by Piyushsahu99** [prajapatihet/donorconnect#10]
**[Pls assign these issues to me so that i can make ch
anges in the project]****
### This is how it look after change 
![Screenshot 2024-10-02 181016](https://github.com/user-attachments/assets/eeca4a58-724e-4780-874d-9587c7a09151)

**Comment by prajapatihet** [comment]
There is no navigation bar in project till now and it is mobile application so make according to that
