### ISSUE TITLE
[Feature Request]: Handle Application theme Correctly

### ISSUE THREAD

**Issue by prajapatihet** [prajapatihet/donorconnect#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Allows users to switch between Light, Dark, or Custom themes, providing a personalized and visually comfortable interface.

### Use Case

Enables manual or system-based theme switching, scheduled changes, and high-contrast modes for accessibility.

### Benefits

Improves user experience, reduces eye strain, saves battery, and ensures consistency with system preferences.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by OmDixit2107** [comment]
Hey, can you assign me this issue , I want to give it a try.

**Comment by prajapatihet** [comment]
@OmDixit2107 make sure all page/screen theme handle correctly and displayed data
Don't change any backend-logic just make changes in UI
