### ISSUE TITLE
[Documentation Update]: Add File Storage Documentation to README

### ISSUE THREAD

**Issue by banasmita24** [prajapatihet/donorconnect#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Enhance the README to include a section that details the structure and purpose of files and folders within the project. This documentation will help new contributors and maintainers understand where to find specific files.

### Suggested Change

- List key folders and files.
- Include any subdirectory structures if relevant, and explain the organization.
- README includes a "File Structure" or "Project Structure" section.
- New contributors can understand the purpose of each file/folder from the documentation.

### Rationale

This will help new contributors and team members understand the organization and purpose of different files in the project.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
It is already there in project_structure.md file

**Comment by banasmita24** [comment]
It's usually present in the readme.md file. @prajapatihet

**Comment by prajapatihet** [comment]
It is so long so it in separate file
