### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [prajapatihet/donorconnect#118]
Issue Description

adding Stargazers and Forkers section to readme.md

Suggested Change

we can add Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

![2024-10-23 (9)](https://github.com/user-attachments/assets/7c00ef9e-3ef2-4ad7-89ba-75e32657e9c8)
please @prajapatihet assign with level 2 or level 3 label

**Comment by prajapatihet** [comment]
Don't add documentation and workflow in repo if you really want to work then try to contribute into project not on docs and workflow
