### ISSUE TITLE
[Documentation Update]: Want to add security

### ISSUE THREAD

**Issue by Dipanita45** [prajapatihet/donorconnect#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Add security

### Suggested Change

security of the website

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [ ] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Which type of security? Can you please explain more about it

**Comment by Dipanita45** [comment]
I want to add necessary security to protect the website against the harms
according to this website

**Comment by prajapatihet** [comment]
First of all it is not a website
This repository contains Mobile Application Project

**Comment by Dipanita45** [comment]
Security to protect the app

**Comment by prajapatihet** [comment]
Which security?
How did you perform and explain use case and feature of it

**Comment by Dipanita45** [comment]
Website security

**Comment by Dipanita45** [comment]
Please assign me the issue

**Comment by Dipanita45** [comment]
Please

**Comment by prajapatihet** [comment]
What security explains more

**Comment by Dipanita45** [comment]
Please please assign me

**Comment by Dipanita45** [comment]
Security policy like how to deal with vulnerability, .... Etc 

Please assign me the issue

**Comment by prajapatihet** [comment]
If you want to start work on it processed but merge PR is depending upon reviewing the PR if it doesn't fit for the project then I will not merge

**Comment by Dipanita45** [comment]
Okay

**Comment by Dipanita45** [comment]
Please assign me this issue 
@prajapatihet
