### ISSUE TITLE
Build logic for login and signup page

### ISSUE THREAD

**Issue by prajapatihet** [prajapatihet/donorconnect#12]
Add proper login and signup logic functionality using any database to fetch data and validate it.
Also check possible error handling and show snakbar or Toast to show errors

**Comment by ritik6559** [comment]
i can work on this, under the label of hactoberfest and gssoc and also please assign a level to it.

**Comment by prajapatihet** [comment]
Can you explain how and which database you use?

**Comment by ritik6559** [comment]
firebase, supabase or even nodejs and mongo

**Comment by prajapatihet** [comment]
You can proced with firebase and go throught login and sign-up and recently builds profile page so also consider that fields

**Comment by ritik6559** [comment]
Do you have any design for login and signup pages

**Comment by ritik6559** [comment]
Can we talk on linkedin

**Comment by prajapatihet** [comment]
you can build at your own but make it simple and enhanced

**Comment by ritik6559** [comment]
ok Sure

**Comment by ritik6559** [comment]
do i have to do it with bloc and cubit or i can use other state management?

**Comment by prajapatihet** [comment]
you can use any of this just keep in mind output will meets requirement

**Comment by ritik6559** [comment]
Ok ok

**Comment by ritik6559** [comment]
hey work is done, but while committing, it is showing access not granted so can you grant access or create  a new branch

**Comment by ritik6559** [comment]
pull request raised

**Comment by prajapatihet** [comment]
there is one suggestion add log out button as once account created i can't log out

**Comment by ritik6559** [comment]
on which screen should i add that button?

**Comment by prajapatihet** [comment]
as of now create on homescreen appbar right side of Text

**Comment by ritik6559** [comment]
done

**Comment by prajapatihet** [comment]
and remember in future if you get any project
make sure your all sensiitive data like api-keys, secret-code etc mut be in gitignore to avoid data expose

**Comment by prajapatihet** [comment]
this time i handle it don't worry @ritik6559

**Comment by ritik6559** [comment]
Ok thanks
