### ISSUE TITLE
Fetch data from bloodbank API and Display

### ISSUE THREAD

**Issue by prajapatihet** [prajapatihet/donorconnect#13]
Find Proper API from internet and fetch relevent information from it and display into screen
Add search and filter functinality so User can easily find they required or nearby blood banks

**Comment by may-tas** [comment]
there is an official API from data.gov but the portal is undergoing maintenance so I was unable to generate API key

**Comment by Mayank202004** [comment]
Created a page for locate bloodbanks . Navigation added when clicked locate bloodbank on home screen. Currently this page is blank as API is under maintenance. Assign me to create pr for partial completion.

**Comment by may-tas** [comment]
hey, @prajapatihet as I mentioned at the start the portal is done with maintenance , Now i would like to solve this issue and display blood banks in locate blood bank file.
by the way the name of the file written does not follow the naming convention so I would like to change that too.
Please assign me this issue under hactoberfest , hactoberfest-accepted and gssoc-ext label.
I will complete the work on time.

**Comment by atharvajahagirdar21** [comment]
Hi! I would like to work on this issue . I believe I can help resolve it and will keep the community updated on my progress. Thank you!

**Comment by prajapatihet** [comment]
@may-tas Start working on it

**Comment by may-tas** [comment]
sure.
