### ISSUE TITLE
Screen for Donation camps or other Events

### ISSUE THREAD

**Issue by prajapatihet** [prajapatihet/donorconnect#14]
Show a list of nearby blood donation camps organized by hospitals or NGOs, with details such as date, time, and location.
Use geolocation to list camps closest to the user and allow them to sign up for participation.
Add a "Navigate to Map" button for event location.

**Comment by lavitratyagi1** [comment]
The data of blood donation camp is stored in the database or have to fetch from somewhere else?

**Comment by prajapatihet** [comment]
from database

**Comment by lavitratyagi1** [comment]
> from database
> display live or upcoming camps/events for registering
> and for past camps/events there is option like view past events but unavailable for register

Ok I can work on it I just need some more information we can connect on LinkedIn if you can share with me more information

**Comment by prajapatihet** [comment]
You can find it on github-profile

**Comment by lavitratyagi1** [comment]
please assign this to me under hacktober fest and gssoc tag i want to work on it

**Comment by atharvajahagirdar21** [comment]
Hi! I would like to work on this issue (#issue-number). I believe I can help resolve it and will keep the community updated on my progress. Thank you!

**Comment by lavitratyagi1** [comment]
> Hi! I would like to work on this issue (#issue-number). I believe I can help resolve it and will keep the community updated on my progress. Thank you!

sorry i am already working on it

**Comment by lavitratyagi1** [comment]
You want this page to open with this button 

![image](https://github.com/user-attachments/assets/37946883-69d5-4b2b-86f1-27d2bbd4f10a)

or should i add a new **HomeCard** in **homePage** or if you want any other to access that page you can tell me.

**Comment by lavitratyagi1** [comment]
@prajapatihet can you please tell me database structure and which database you want to use.

**Comment by prajapatihet** [comment]
if you comfortable with mongo(using cluster) then processed with it but make sure you create proper schema and data models as migrate my complete project into mongo later on in future

**Comment by lavitratyagi1** [comment]
I have created a UI can you please check it and if you want any changes you can tell me now
![image](https://github.com/user-attachments/assets/9af0ce3f-f1a9-42be-bb18-6fc5fecc3efd)
![image](https://github.com/user-attachments/assets/ff391bfc-35ba-4182-9e95-89cae5966d97)

i have created this page with light mode as your complete app is in light mode.

**Comment by lavitratyagi1** [comment]
you want to make it like this page should open when click on this icon 
![image](https://github.com/user-attachments/assets/084ee1d6-1134-45d9-8fdd-fa83514a3f27)
but i think it should be in this 
![image](https://github.com/user-attachments/assets/315817af-0679-44de-8be2-2cb3544ca5fc)
i have done in this one if you want i can change that but i think in this camps button in bottom navbar it should show list of registered camps . 
Just give me a conformation how to do it i will fix it

**Comment by prajapatihet** [comment]
In camps section

Because for bloodbanks it should be authorised hospital or bloodbanks 

Camps will be periodically or 1-2 days and facilitate by hospital and NGOs

**Comment by lavitratyagi1** [comment]
ok i will go for it then 
any more changes in ui ?

**Comment by lavitratyagi1** [comment]
ok sure i will also add a floting button 
and in terms of user experience what should i enhance like should i change colour or design or size or something else

**Comment by prajapatihet** [comment]
on intial page only DriveName, dateTime and location only then on click that 
display some-pop/bottomsheet/new-screen with all details associated with any organization or verified or not rating from previous organized drive reviews, images(Not Complusory), register, navigate(Map)

like this and also handle past drive like if date gone then remove it or make on top state "View Past Drives" etc

**Comment by lavitratyagi1** [comment]
I think this is a large work so can you please rethink and mark this one as level 3

**Comment by prajapatihet** [comment]
I will update later

**Comment by lavitratyagi1** [comment]
![image](https://github.com/user-attachments/assets/3f65d7fe-84a6-49bb-974e-20ab12668daf)
Is this design satisfy your need?

**Comment by prajapatihet** [comment]
looks good
just make sure it handle date and remove back-arraow at topLeft corner

**Comment by lavitratyagi1** [comment]
![image](https://github.com/user-attachments/assets/d6326ee6-1c2a-45ef-85dc-2834a965097a)
This is also a good style to display which one is better i will keep it

**Comment by prajapatihet** [comment]
status?
and pull the latest code from remote repo to avoid confilt issues at later stage

**Comment by lavitratyagi1** [comment]
Everything is completed just add camps form is remaining. i am working on it

**Comment by lavitratyagi1** [comment]
hey in add camps page how should i get latitude and longitude of the camp location?
like should i directly get it from user in integer format or any other way?

**Comment by prajapatihet** [comment]
> hey in add camps page how should i get latitude and longitude of the camp location? like should i directly get it from user in integer format or any other way?

As it is difficult to get integer as User so i planing instead of finding using latitude and longitude we go for address text as query and parse throght url like
![image](https://github.com/user-attachments/assets/fbfe1827-5fe4-4ce2-9348-34380d64a5ea)
For now no need to implement for this
If you can do it then go ahead otherwise leave it

**Comment by lavitratyagi1** [comment]
> > hey in add camps page how should i get latitude and longitude of the camp location? like should i directly get it from user in integer format or any other way?
> 
> As it is difficult to get integer as User so i planing instead of finding using latitude and longitude we go for address text as query and parse throght url like
> ![image](https://github.com/user-attachments/assets/fbfe1827-5fe4-4ce2-9348-34380d64a5ea)
> For now no need to implement for this
> If you can do it then go ahead otherwise leave it
> 

What I have implemented is when the user is adding camp details user current lat and log will get added in the database of camp details so it will be used to locate using google map so when the user clicks on navigate it will open the Google maps route.

**Comment by prajapatihet** [comment]
No problem I merge this implementation 
And for location I will raise and issue if in future it's required
