### ISSUE TITLE
Screen for User Profile Setup

### ISSUE THREAD

**Issue by prajapatihet** [prajapatihet/donorconnect#15]
After registration, users will be directed to a profile page where they can fill in more details like medical history, current medications, allergies, etc.
Fields like blood type and whether they're willing to donate blood or organs will be collected.
Users can update their information at any time. Profile settings should include the ability to turn on/off notifications for donation-related events.

**Comment by may-tas** [comment]
Hy, I would like to work on this issue , Can you please add Hactoberfest and gssoc tags.

**Comment by may-tas** [comment]
hy, just noticed that there is no navigation happening when I press the registration button, Its missing 
 Navigator.push(
          context, MaterialPageRoute(builder: (context) => const HomePage()));
Also , I think this is very inefficient to use , How about we use GoRouter package?
Can I open an issue for it?

**Comment by prajapatihet** [comment]
Don't use GoRouter 
as of now just work with MaterialPageRoute in future if it require then we will proced with it 
as app don't much screen
Now just focus on Profile screen building

**Comment by may-tas** [comment]
okay thanks, and what about navigation from registration page , should i add navigation on my own?
Also in profile page , for state management i was using Cubit, Is there any preference for other state management tools.
if yes, do tell.

**Comment by prajapatihet** [comment]
Yes you can add your navigation but make sure it will properly works
You can use cubit and if it is required you can use shared-preference for caching

**Comment by may-tas** [comment]
Okay Thanks

**Comment by prajapatihet** [comment]
@may-tas are you comfotable with firebase, supabase or even nodejs and mongo??

**Comment by prajapatihet** [comment]
If you encounter any new issue or problem raise new issue @may-tas 
now i am closing this issue

**Comment by may-tas** [comment]
Okay Got it.
