### ISSUE TITLE
Password Not Obscured on Login and Sign-Up Pages

### ISSUE THREAD

**Issue by T-Soni** [prajapatihet/donorconnect#16]
### **Description**

When entering the password in both the Login and Sign-Up pages, the password text is not obscured (masked). This exposes the password in plain text, potentially compromising user privacy and security.

### **Expected Behavior**

The password field should obscure the text (mask it) by displaying dots or asterisks (●●●●) instead of the actual characters, ensuring that the password is hidden while typing.

### **Steps to Reproduce**

1. Navigate to the Login or Sign-Up page.
2. Enter a password in the password field.
3. Observe that the password is displayed as plain text instead of being obscured.

### **Actual Behavior**

The password is shown in plain text while typing, which can lead to accidental password exposure.

### **Proposed Solution**

Implement a password obscuring mechanism in the password fields on both pages to mask the password input.

**Comment by T-Soni** [comment]
I am a **GSSoC Extended** contributor and would like to work on this issue. Please assign this to me under the labels **GSSoC** and **Hacktoberfest**.

**Comment by T-Soni** [comment]
Hi! I would like to request adding a level to this issue for GSoC.

**Comment by prajapatihet** [comment]
i can't add any level in this issue as for making password to Obscured we just have to add only one attribute
for assigning level to PR i also have to check complexity of that issue
