### ISSUE TITLE
Creating a login and registration page

### ISSUE THREAD

**Issue by vinit105** [prajapatihet/donorconnect#2]
Login/Registration Page:
Allow users to register using their email, phone number, and a password.
Add an option for multi-factor authentication (MFA) for enhanced security.
Include two checkboxes for "Available for Blood Donation" and "Available for Organ Donation."
Required fields: Email, Phone Number, Age, Gender, Blood Group.

Assign this task to me

**Comment by vinit105** [comment]
also why cant i give label to it, i am new to this

**Comment by prajapatihet** [comment]
@vinit105 only project admin have access to assign issue and labels so contributors raise an issue and after reviewing issue and its complexity project admin assign it to contributor

**Comment by prajapatihet** [comment]
@vinit105 How much time you required to complete this task?

**Comment by vinit105** [comment]
Today evening

**Comment by prajapatihet** [comment]
Include two checkboxes for "Available for Blood Donation" and "Available for Organ Donation."
Required fields: Email, Phone Number, Age, Gender, Blood Group.

This two is remaining so complete it @vinit105
