### ISSUE TITLE
Add contributor in Readme.md

### ISSUE THREAD

**Issue by sakshamsaraf23** [prajapatihet/donorconnect#24]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared
![373815323-76171289-5b05-48c4-a5be-dc8ac76d70cb](https://github.com/user-attachments/assets/d03d69f9-6a7a-462d-b96d-d509db4d727b)
@prajapatihet can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it

**Comment by sakshamsaraf23** [comment]
sir do add the label so my contribution can count

**Comment by prajapatihet** [comment]
i can't add any level label as it is just documentation change

**Comment by sakshamsaraf23** [comment]
ok sir do review my PR.
