### ISSUE TITLE
Enhance readme,md

### ISSUE THREAD

**Issue by Aditijainnn** [prajapatihet/donorconnect#26]
Enhancing readme.md file 
assign this issue to me under gssoc ext and hacktoberfest

**Comment by prajapatihet** [comment]
Explain more about issues!!

**Comment by Aditijainnn** [comment]
> Explain more about issues!!

it can have go to top toggle
also ince its too long to scroll through adding dropdowns

**Comment by prajapatihet** [comment]
Instead of writing issues in readme file, raise an issue in issue section is more convenient

**Comment by Aditijainnn** [comment]
> Instead of writing issues in readme file, raise an issue in issue section is more convenient
> 
> If you want to really contribute then go with coding not documentation

ok
