### ISSUE TITLE
Screen Updates, Authentication Updates

### ISSUE THREAD

**Issue by Reboot2004** [prajapatihet/donorconnect#27]
Areas of Concerns:
1. Signup Page:
- Doesn't check authenticity of info that is entered.
- Implement an email validation logic.
2. Login Page:
- logging in causes an error
3. Implement a Screen for Details about blood donation and improve the update profile section as well

Ideas wanted to implement:
1. Add Authentication and validation logic in Signup
2. Implement screen for details about blood and organ donation
3. Improve the Update profile section
4. Add logic for Forgot Password

**Comment by Reboot2004** [comment]
Plz assign me this issue? under GSSOC extd 2024
If any of the above areas overlap with currently open issues. Please suggest

**Comment by prajapatihet** [comment]
i already assign this someone else ##12 issue

**Comment by Reboot2004** [comment]
I see Signup and Login have been assigned 
It seems like the Screen dealing with Blood and organ donation details has not been talked about much unlike screens dealing with details about various events and etc.
If it works, i would like to work on that screen

**Comment by prajapatihet** [comment]
elaborate more about issue

**Comment by Reboot2004** [comment]
![Screenshot_2024-10-06-14-27-08-30_8bff991cba0e7c4ed3f8108502f4292d](https://github.com/user-attachments/assets/17bba9e2-fa7d-439d-9fd0-5c4b225ea857)
Wanted to create the screen for learn about donating

**Comment by prajapatihet** [comment]
ok
create new issue with this and while creating this use every possible things like bold text, bullets points images etc
