### ISSUE TITLE
White Screen Displayed After Login

### ISSUE THREAD

**Issue by lavitratyagi1** [prajapatihet/donorconnect#28]
After successfully logging into the application, a white screen is displayed instead of navigating to the intended page. The issue persists on multiple devices and across different user accounts. No errors or exceptions are visible in the logs during the transition. The expected behavior is to navigate to the home/dashboard screen after login.

Steps to Reproduce:

1. Open the app and navigate to the login page.
2. Enter valid credentials and tap the "Login" button.
3. Observe the white screen displayed after the login attempt.

**Expected Result**: The app should navigate to the home/dashboard page after a successful login.

**Actual Result**: A white screen is displayed, and the app appears to be stuck.

**Comment by prajapatihet** [comment]
I will assign you after login and signup will created as it is already in process

**Comment by lavitratyagi1** [comment]
> I will assign you after login and signup will created as it is already in process

Is there anything on which i can work on like is there anything that you want to implement or not implemented yet or any issue in this app.
I am good at flutter and can work on a wide range of flutter projects

**Comment by prajapatihet** [comment]
check out issue 13 and 14

**Comment by Srilochan7** [comment]
@lavitratyagi1  i am a gssoc contributor please assign me this issue

**Comment by lavitratyagi1** [comment]
> @lavitratyagi1  i am a gssoc contributor please assign me this issue

Bro I am also a contributor and I have created this issue
