### ISSUE TITLE
Screen for Learn more about Donating 

### ISSUE THREAD

**Issue by Reboot2004** [prajapatihet/donorconnect#31]
Describe information about donation, best practices and cautions

**Comment by Reboot2004** [comment]
Assign me this issue with GSSOC extd 2024, hacktoberfest and level tag.

**Comment by prajapatihet** [comment]
assign level label after reviewing PR

**Comment by Reboot2004** [comment]
I see the latest commits were related to hiding the "firebase_options.dart". I do understand the need to hide such information but for the ease of development, can u update the repo with the file.

**Comment by atharvajahagirdar21** [comment]
Assign me this issue with GSSOC extd 2024, hacktoberfest and level tag.

**Comment by prajapatihet** [comment]
@Reboot2004 Staus?

**Comment by Reboot2004** [comment]
@prajapatihet  Under Progress

**Comment by prajapatihet** [comment]
@may-tas you can processed!!!

**Comment by may-tas** [comment]
Thanks, will do.
