### ISSUE TITLE
Input Validation during SignUp

### ISSUE THREAD

**Issue by RebellionR2** [prajapatihet/donorconnect#33]
### **Is there an existing issue for this?**
_✔️No, I have searched the existing issues_

### **What happened?**

https://github.com/user-attachments/assets/3dfbfdb3-6f94-4d81-a015-dd6e8a41bf9d

So the issue is that when signing up we are entering email and other details but its not throwing any error or popup if we are entering random values. Like for email the format should be  : somthing245@mail.com  but it is even excepting test24. 

Also for the Mobile number there should be atleast 10 digit but here i can get away with 100 also as shown in video.

Kindly assign me this issue so that i can solve it. Also mark it for ggsoc and hactoberfest so that it will count in my score.

### **_Record_**

_✔️ I agree to follow this project's Code of Conduct
✔️ I'm a GSSOC'24-Ext  contributor
✔️ I want to work on this issue_

**Comment by RebellionR2** [comment]
Hi, 

-> Kindly assign the issue to me. 
-> Kindly add labels of GSSOC'24-ext and hacktoberfest

**Comment by prajapatihet** [comment]
Kindly check once database is connected

**Comment by prajapatihet** [comment]
As we made login and signup backend to store data
So keep in mind do not change that code and add validation to fields 
And try with your firebase setup like remove previously created firebase file like google-services, firebase_options, firebase.json files etc try with your setup

**Comment by ritik6559** [comment]
i can work on it

**Comment by prajapatihet** [comment]
@RebellionR2 what's your status?

**Comment by ritik6559** [comment]
firebase authentication have been resolved

**Comment by may-tas** [comment]
I can work on this.

**Comment by prajapatihet** [comment]
Keep considering these points 

As we made login and signup backend to store data
So keep in mind do not change that code and add validation to fields
And try with your firebase setup like remove previously created firebase file like google-services, firebase_options, firebase.json files etc try with your setup

**Comment by RebellionR2** [comment]
Sure @prajapatihet , stay assured, I won't touch the backend part. Also i am setting up firebase if i face any issue will let you know.

**Comment by RebellionR2** [comment]
@prajapatihet  before merging kindly add label of Level also, otherwise it won't count.
