### ISSUE TITLE
[Feature Request]: Inefficient Login Flow

### ISSUE THREAD

**Issue by lavitratyagi1** [prajapatihet/donorconnect#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Current Behavior: When opening the app, it initially loads the login page. Upon clicking the login button, the app checks whether the user is already logged in. If the user is logged in, they are redirected to the homepage. If not, they remain on the login page.

Proposed Enhancement: I suggest modifying the flow to improve the user experience. Instead of starting with the login page, the app should directly open the homepage. Once on the homepage, the app should check if the user is logged in:

If the user is logged in, they remain on the homepage.
If the user is not logged in, they are redirected to the login/signup page.

### Use Case

Benefits:
Smoother user experience by avoiding unnecessary steps for logged-in users.
Reduces the friction of always seeing the login page on app launch.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Status?
