### ISSUE TITLE
[Bug]: Learn About Donating not working 

### ISSUE THREAD

**Issue by RebellionR2** [prajapatihet/donorconnect#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Learn About Donating is not  working when i am clicking on it. 
Kindly suggest what information must be added in that title after it opens. 
I have added a video of bug. 

### Expected behavior

Expected Behavior is that a new page should open with details about blood donation 

### Add ScreenShots

https://github.com/user-attachments/assets/6000feec-8cde-4518-b5db-b27f6c6805b4

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by RebellionR2** [comment]
Kindly Assign this issue to me.
Also please suggest what should i add in the Learn About Donating screen. 

Kindly add Hacktoberfest, ggsoc-ext and level tag

**Comment by prajapatihet** [comment]
It's already assigned
