### ISSUE TITLE
to add light and dark mode toggle 

### ISSUE THREAD

**Issue by sv410** [prajapatihet/donorconnect#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 I propose implementing a dark and light mode toggle on our website. This feature would allow users to easily switch between dark and light themes based on their preference or environment. It enhances the user experience by providing a comfortable viewing option in different lighting conditions.

### Use Case

Manual CSS Switch: Manually change the CSS files for dark and light modes, but this approach is cumbersome and not user-friendly.

Browser Extensions: Relying on browser extensions for dark mode, but this isn't consistent across all users and browsers.

JavaScript Libraries: Use a third-party JavaScript library for theme switching, but this can be overkill for a simple feature.

### Benefits

User-Friendly Interface: The toggle button should be easily accessible and intuitive, located in a prominent position like the header or a fixed navigation bar.

Smooth Transition: The transition between dark and light modes should be smooth and seamless, using CSS transitions to avoid sudden changes that can be jarring to the eyes.

Consistent Design: Ensure all elements, such as text, background, and buttons, are adjusted for both modes to maintain readability and visual appeal.

Accessibility: Consider color contrast and readability to ensure the design is accessible to all users, including those with visual impairments.

### Add ScreenShots

![WhatsApp Image 2024-10-12 at 6 03 50 PM](https://github.com/user-attachments/assets/a43e8724-b5a2-4aa3-a420-07c20dc4b354)
![WhatsApp Image 2024-10-12 at 6 02 58 PM](https://github.com/user-attachments/assets/84bf8fcb-24be-4799-b849-b225b1424128)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Are you ware what we are building?
its is mobile application not web project
If you have any prior experience with Flutter then we can processed!!!

**Comment by CodewithAnn** [comment]
> Are you aware what we are building? its is mobile application not web project If you have any prior experience with Flutter then we can processed!!!

you(@prajapatihet ) can assign this to me. I can handle it very smoothly in flutter.

**Comment by CodewithAnn** [comment]
@prajapatihet may be you assigned someone else by mistakenly?

**Comment by sv410** [comment]
@prajapatihet Yes, I'm aware that we're building a mobile application and not a web project. I have experience with Flutter and am excited about the opportunity to contribute to this project. ill soon update it when i am done

**Comment by prajapatihet** [comment]
I am sorry @CodewithAnn for confusion but i have to assign who came/raise an issue first

**Comment by AnshuWorld** [comment]
Please assign me this task under gssoc24 extd

**Comment by prajapatihet** [comment]
@sv410 status?

**Comment by sv410** [comment]
@prajapatihet i have done it pls check... pls add level 3!

**Comment by prajapatihet** [comment]
where is PR?

**Comment by prajapatihet** [comment]
@sv410 status?

**Comment by CodewithAnn** [comment]
> I am sorry @CodewithAnn for confusion but i have to assign who came/raise an issue first

@prajapatihet  If he/she not working on this issue please assign this to me. 
### Proof of work from last repository 

https://github.com/user-attachments/assets/7e70382d-464e-43f1-84f2-827a4933f4ce

**Comment by prajapatihet** [comment]
@CodewithAnn you may processed
