### ISSUE TITLE
[Feature Request]: dark and light mode

### ISSUE THREAD

**Issue by WednesdaySP** [prajapatihet/donorconnect#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to incorporate dark and light mode functionality in the application to enhance its visual appeal and improve the overall user experience.

### Use Case

will enhance application user interface

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Why did you closed this issue?

**Comment by WednesdaySP** [comment]
@prajapatihet because someone already created the same issue
