### ISSUE TITLE
[Feature Request]:  Add localization in app so language never be a barrier

### ISSUE THREAD

**Issue by CodewithAnn** [prajapatihet/donorconnect#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Localization or AKA internationalization simply allows people to choose a language they understand.  

### Use Case

Localization or AKA internationalization helps people to use this app without worrying about whether they know English or not, they can use it in their own language too. It is a small gesture but means a lot for them a respect the language they understand 

### Add ScreenShots

proof of work from previous projects.

https://github.com/user-attachments/assets/b342cd2b-b9e5-432b-8ef3-23f9a357f476

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by CodewithAnn** [comment]
@prajapatihet please assign this issue to me, so that I can help your user to use your app better without any language barrier.

**Comment by CodewithAnn** [comment]
@prajapatihet  work done 👍😁

**Comment by prajapatihet** [comment]
i will review tomorrow and merge it

**Comment by CodewithAnn** [comment]
> i will review tomorrow and merge it

okay
