### ISSUE TITLE
[Bug 🐞]:  improper navigations between screen

### ISSUE THREAD

**Issue by WednesdaySP** [prajapatihet/donorconnect#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently the navigation flow in app is not in proper order, from profile screen user directly goes to login screen which should not happen, also there is no need of back button in profile screen.
and similarly user navigates to signup screen from profile screen, and so on.

### Expected behavior

Once a user has logged in to the application, he/she should only be able to go to the login/signup screen if he/she logs out of the application.

### Add ScreenShots

https://github.com/user-attachments/assets/f221fe9f-1f25-4b06-886d-fa714ed2cdd0

### On which device are you experiencing this bug?

Android, iPhone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by WednesdaySP** [comment]
@prajapatihet I would like to work on this issue, kindly assign me.

**Comment by prajapatihet** [comment]
Also handle all navigation part with/using push, pop, pushReplacement etc
If possible then also handle page transist for smooth navigation effect if you can!!

**Comment by WednesdaySP** [comment]
@prajapatihet  sure I will 😊.
