### ISSUE TITLE
[Bug 🐞]: password visibility issue in signup screen

### ISSUE THREAD

**Issue by WednesdaySP** [prajapatihet/donorconnect#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As of now, the password entered in the password field is not visible to user which makes it difficult for user to ensure if he has written similar passwords in password and confirm password fields.

Also, the password validation message is not properly visible on the app screen, making it difficult to understand the password validation criteria.the user, making it difficult

### Expected behavior

There should have been a visible password btn through which the user could see his inserted password easily, and make required changes.

The validation msg should be properly displayed to avoid any kind of misguidance to the user.

### Add ScreenShots

![WhatsApp Image 2024-10-13 at 16 51 31_ef7e3c4e](https://github.com/user-attachments/assets/ca80f278-0dd1-4e15-8537-ad0165260651)

### On which device are you experiencing this bug?

Android, iPhone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Add icon for visibility and build proper logic for passward validation

**Comment by prajapatihet** [comment]
Status?

**Comment by WednesdaySP** [comment]
working on it, will be completed by tonight.
