### ISSUE TITLE
[Feature Request]:  integrating forgot password functionality 

### ISSUE THREAD

**Issue by WednesdaySP** [prajapatihet/donorconnect#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add functionality to the forget password button present in the login screen.

### Use Case

This will enhance user experience and as it is very common to forget passwords, this feature will be of great use for every user.

### Benefits

Increase app usability and improved user authentication.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by ezsarthak** [comment]
I can work on this issue. I would to love contribute to this project
