### ISSUE TITLE
I want to create the select your blood type screen

### ISSUE THREAD

**Issue by 17arindam** [prajapatihet/donorconnect#6]
i want to create this select your blood type screen 
![image](https://github.com/user-attachments/assets/308e313d-ff3e-441e-8388-05c28d63c920)
can you assign me this issue @prajapatihet

**Comment by prajapatihet** [comment]
It is just for reference image that i put on my readme file and it is associated with registration screen 
i already assign to someone else if they didn't complete it i will assign it you but you have to complete complete login and registration screens

**Comment by Piyushsahu99** [comment]
I am intrested to work on this issue can you pls assign it to me.

**Comment by Piyushsahu99** [comment]
> i want to create this select your blood type screen ![image](https://private-user-images.githubusercontent.com/65901047/372742299-308e313d-ff3e-441e-8388-05c28d63c920.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjMwNDQsIm5iZiI6MTcyNzg2Mjc0NCwicGF0aCI6Ii82NTkwMTA0Ny8zNzI3NDIyOTktMzA4ZTMxM2QtZmYzZS00NDFlLTgzODgtMDVjMjhkNjNjOTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDA5NTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOTlhNmZlYzcyNTMwZGVjMzVjYzFhNDcwOTYxOGYzN2IwNDRkY2YwM2NmOWUwNTY2MmQzNjAzM2YyNWUwMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t6j1s8dCZDj_mEGN4Rf6ClV-9VUhg29LtCHfvPAhM3k) can you assign me this issue @prajapatihet

Can you pls label it

**Comment by prajapatihet** [comment]
Please read carefully the readme file and previous comments
