### ISSUE TITLE
[Feature Request]: Bottom Navigation Bar improment

### ISSUE THREAD

**Issue by ezsarthak** [prajapatihet/donorconnect#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to make the bottom navigation bar more interactive and animated and also user can swipe between pages with just right or left swipe on the home screen

### Use Case

This will add animation while changing the pages of the bottom navigation bar and while changing page using swipes

### Benefits

This will add a great user experience and interactive UI

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
update your homepage.dart code with current updated present on github(no need to push again just update it)

Otherwise i merged and solve the problems
