### ISSUE TITLE
[Feature Request]: Adding Login by Google Account

### ISSUE THREAD

**Issue by ezsarthak** [prajapatihet/donorconnect#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Users can directly Login /Signup using Google account

### Use Case

Users can Login/Signup without a password and there will be no need to enter details like name manually

### Benefits

Users can Login/Signup fast and password less hassle-free

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Progress status?

**Comment by prajapatihet** [comment]
@ezsarthak please reply within 12hrs otherwise I will assign next one

**Comment by ezsarthak** [comment]
You can assign to him. Thanks

**Comment by prajapatihet** [comment]
@Dhruv80576 Please go ahead
