### ISSUE TITLE
[Bug]: Preserving activity history even after authentication

### ISSUE THREAD

**Issue by Dhruv80576** [prajapatihet/donorconnect#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whenever back button is pressed it returns to its previous activity even after logging in and pressing back button app returns back to its login activity.

### Expected behavior

Application should forget previous navigation history after certain events after successful.

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
It is already assign as inefficient login flow
