### ISSUE TITLE
[Bug]: Profile not updated on logging later.

### ISSUE THREAD

**Issue by Dhruv80576** [prajapatihet/donorconnect#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whenever we reopen application after successful login, profile page doesn't update and no information is retreived.

### Expected behavior

It should show user information on reopening application from the firebase db.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/061d0de4-7128-41f6-8562-3f54c9e58bb8)

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
kindly pull newly updated code from remote repo then try
