### ISSUE TITLE
[Feature Request]: Creating a Calendar for featuring upcoming camps.

### ISSUE THREAD

**Issue by Dhruv80576** [prajapatihet/donorconnect#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implementing a calendar for upcoming events and displaying their information in details.

### Use Case

- It will help in showcasing events to the user for active participation
- It will help in increasing reach of events.

### Add ScreenShots

Sample ui.
![image](https://github.com/user-attachments/assets/fe3431c8-0c25-45c7-a239-511d31a44752)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
I will assign after camps and events page created as it is already in progress

**Comment by prajapatihet** [comment]
pull the latest commit from repo and on appbar(right) make calender icon and try to implement this feature on it and upcoming camps and events display on calender

If you want to continue on this issue then reply back!!!
