### ISSUE TITLE
I want to add a link related to the project for better understanding .

### ISSUE THREAD

**Issue by Piyushsahu99** [prajapatihet/donorconnect#7]
https://piyushsahu99.github.io/donorconnect/  
here it is the link for readme file

**Comment by prajapatihet** [comment]
which type of link?

**Comment by Piyushsahu99** [comment]
Link for the app

**Comment by prajapatihet** [comment]
like App Screen designs?

**Comment by Piyushsahu99** [comment]
To showcase how our project is working

**Comment by lavitratyagi1** [comment]
Can you please specify it more clear. 
You want to add this link in app or in readme file if in readme file then which type of link?

**Comment by geetanjalidubey9** [comment]
pls aasign this task to me
