### ISSUE TITLE
[Bug]: Wrong Errors Flashing When Signing Up

### ISSUE THREAD

**Issue by RebellionR2** [prajapatihet/donorconnect#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The App is working fine when a new user is signing up with unique Email Address but when a User tries to Register with existing Email the App is displaying Wrong errors like "Name can not be empty", Email blank or Wrong. 

### Expected behavior

It should only Display that Email Already exist.

### Add ScreenShots

https://github.com/user-attachments/assets/bf65d6d5-7409-4e02-aea9-0f977e444671

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by RebellionR2** [comment]
Kindly Assign this issue to me, With tagging of Hactoberfest, gssoc-ext and level.

**Comment by Dhruv80576** [comment]
@prajapatihet 
Can i work on it if current assignee is not interested??

**Comment by prajapatihet** [comment]
@RebellionR2 are you working on it and when you complete it?
If not I will assign to others!!

**Comment by prajapatihet** [comment]
@Dhruv80576 you may processed
