### ISSUE TITLE
[Bug]: Redirecting to Login and Signup page on reopening the application

### ISSUE THREAD

**Issue by Dhruv80576** [prajapatihet/donorconnect#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whenever a user login and again restart the application signup and login page is opened instead of home page.

### Expected behavior

If the user is authenticated it should open home page

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
It is already done in latest commit check it out
