### ISSUE TITLE
[Feature Request]: on campus page

### ISSUE THREAD

**Issue by singhtrivendra** [prajapatihet/donorconnect#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to work on capus page for updating ui styling and and want to upade some changes on add form on campus page

### Use Case

UI will be more attractive i know many styling widget and flutter animation for smooth transition so kindly assign me to work on campus page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by singhtrivendra** [comment]
kindly assign me

**Comment by prajapatihet** [comment]
more info about on-campus page?
