### ISSUE TITLE
[Feature Request]: on search page 

### ISSUE THREAD

**Issue by singhtrivendra** [prajapatihet/donorconnect#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i wnat to make change on search page i have idea of adding features on search page :-
Two List tiles one for blood bank 
2nd for blood donater clicking on which can open two such forms you can see in photo given
![Screenshot 2024-10-18 202118](https://github.com/user-attachments/assets/c00dd02b-36d4-44a2-a389-69ac4aa22456)

### Use Case

adding and seach anf filter to it also

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by singhtrivendra** [comment]
@prajapatihet assign me this

**Comment by singhtrivendra** [comment]
i have design new saerch screen but i unable to find bottom navigation bar file to connect it in the app folders @prajapatihet can you guide me where i can find it.
or i simply pull the folder you may connect it.

i have developed UI

![WhatsApp Image 2024-10-19 at 17 40 11_a6bafef0](https://github.com/user-attachments/assets/f05fe213-c2f5-4255-97a5-05fbe1131639)
![WhatsApp Image 2024-10-19 at 17 40 12_25a27761](https://github.com/user-attachments/assets/a9f5d769-734e-41ea-ad3a-338a0f5bea97)
![WhatsApp Image 2024-10-19 at 17 40 12_d2d7dcb9](https://github.com/user-attachments/assets/bf2e07c1-874a-4186-bc08-f065f9894121)

**Comment by prajapatihet** [comment]
Open App ---> HomePage ---> Click on Bloodbank card ---> Open searchBloodbank filter or on top of list of bloodbank make icon for filter and on click of that icon opensearch bloodbank

for search donor ----> make it on home screen bottom-navbar at search section

**Comment by singhtrivendra** [comment]
i just change only search screen not home screen i used same photo you can it according to your choice 
just see it is demo below.
https://github.com/user-attachments/assets/f5cab0da-a6ab-4f25-acde-8e9d522f7829
now i may pull
