### ISSUE TITLE
[Feature Request]: forget password Screen

### ISSUE THREAD

**Issue by singhtrivendra** [prajapatihet/donorconnect#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to Update styling of forget password Screen
and change passwaord Screen

### Use Case

@prajapatihet  kindly assign me to change above issue

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
I am assigning to you don't change actual logic
