### ISSUE TITLE
Add a new feature of lightmode to darkmode icon on navigation bar

### ISSUE THREAD

**Issue by Piyushsahu99** [prajapatihet/donorconnect#9]
**I want to add a feature of light and darkmode icon on navigation bar.

**Comment by prajapatihet** [comment]
there is no navigation bar in project till now

**Comment by Upendra48** [comment]
I would like to request to be assigned to this issue. I am willing to contribute effectively and provide my best efforts to resolve it.
I would like to add a button on top right corner to navigate between light mode and dark mode.
(Please add gssoc-ext 24 and hacktoberfest label)
