### ISSUE TITLE
[Feature Request]: Create AI Chat-Bot

### ISSUE THREAD

**Issue by prajapatihet** [prajapatihet/donorconnect#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

An AI-powered personalized chatbot that provides real-time responses to general healthcare queries and donation-related questionnaires. It offers personalized assistance and engages users with interactive conversations.

### Use Case

Users can ask health-related questions, seek donation opportunities, or inquire about eligibility and processes for donating blood, organs, or other resources.

### Benefits

Enhances user engagement with quick, accurate responses, reduces dependency on manual support, and improves awareness of healthcare and donation programs.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by Dhruv80576** [comment]
@prajapatihet 
I would like to work on it. Can u assign it to me?

**Comment by prajapatihet** [comment]
@Dhruv80576 Don't use any API(like chatgpt, gemini)
build custom chatbot

**Comment by Dhruv80576** [comment]
i can build chatbot but it will be using chatgpt, but i can customize it according to the application requirement using prompt programming.
Tell me what u think?

**Comment by prajapatihet** [comment]
So can you make it using Gemini?

**Comment by Dhruv80576** [comment]
Yes

**Comment by prajapatihet** [comment]
So make it using gemini
