### ISSUE TITLE
[Feature Request]: Automated project structure updation using github workflows, python scripts and action bot

### ISSUE THREAD

**Issue by J-B-Mugundh** [prajapatihet/donorconnect#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Automated project structure updation using github workflows, python scripts and action bot

### Use Case

Currently, we dont have the automated project structure updation in our repository. 

### Benefits

It'll be benefitial for the new commers to understand the project structure from readme itself and reduces the manual work as well. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/26bbda18-4082-4d17-8222-1488fbcdb3fb)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
@J-B-Mugundh Please check it out why workflow not working properly!!!

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh Please check it out why workflow not working properly!!!

I believe github-actions[bot] is being blocked in your repository!

To allow the default `github-actions[bot]` to push to your repository, please follow these steps:

## 1. Enable Write Permissions for GitHub Actions

1. Go to your repository's **Settings > Actions > General**.
2. Under **Workflow permissions**, select **Read and write permissions**.
   - This setting allows the `github-actions[bot]` to push changes to the repository.

## 2. Adjust Branch Protection Rules

If you have branch protection rules enabled, these may block the `github-actions[bot]` from pushing to the branch.

1. Go to **Settings > Branches** in your repository.
2. Select the relevant branch protection rule.
3. Check **Allow GitHub Actions to bypass branch protections**.
   - This permits the bot to push to protected branches if necessary.
   

Let me know if you still face the issue bro! @prajapatihet
