### ISSUE TITLE
[Feature Request]:  To add onboarding page 

### ISSUE THREAD

**Issue by singhtrivendra** [prajapatihet/donorconnect#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![WhatsApp Image 2024-10-21 at 14 28 08_d8ba80c7](https://github.com/user-attachments/assets/72fcb7a4-13a2-4783-8951-62ff6b68e7ff)
![WhatsApp Image 2024-10-21 at 14 28 44_5be33035](https://github.com/user-attachments/assets/ad1766e4-0d72-4847-ad47-8906019e669f)
![WhatsApp Image 2024-10-21 at 14 29 03_f8b55151](https://github.com/user-attachments/assets/468d12e0-c274-4048-834b-995a36fbfbbd)

### Use Case

@mehul-m-prajapati kindly assign me i want to add 3 onboarding page as shown above 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

**Comment by mehul-m-prajapati** [comment]
Here you go @prajapatihet . Assigned it to you.

**Comment by singhtrivendra** [comment]
@prajapatihet assign me above issue
